BrownBiomechanics/Autoscoper

autoscoper/src/ui/autoscoper_resource.qrc
This commit partially reverts 7765bd04d (STYLE: Remove trailing spaces from cmake files) by re-introducing the resource file `autoscoper_resource.qrc`
=> COMP: Fix configuration re-adding inadvertently deleted qrc file

CMake/AutoscoperInstallQt.cmake, CMakeLists.txt, autoscoper/CMakeLists.txt, libautoscoper/CMakeLists.txt
This commit is a follow-up of d076839 (COMP: Set target properties for
output paths)
=> COMP: Update install rules to support custom install destination

CMakeLists.txt, autoscoper/CMakeLists.txt
* Add option `Autoscoper_INSTALL_SAMPLE_DATA` to conditionally copy or install sample_data.
* Add custom target `CopyAutoscoperSampleData` for copying sample_data along side the autoscoper executable.
* Consolidate install rules into the top-level `CMakeLists.txt` and update them to be consistent with the autoscoper executable install rule.
* Closes #27
=> Consolidate handling of sample data

CMakeLists.txt, autoscoper/CMakeLists.txt, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/FilterTreeWidgetItem.cpp, autoscoper/src/ui/GLTracker.cpp, autoscoper/src/ui/GLView.cpp, autoscoper/src/ui/GLWidget.cpp, autoscoper/src/ui/ModelViewTreeWidgetItem.cpp, autoscoper/src/ui/OpenCLPlatformSelectDialog.cpp, libautoscoper/CMakeLists.txt, libautoscoper/src/Filter.hpp, libautoscoper/src/Tracker.cpp, libautoscoper/src/Tracker.hpp, libautoscoper/src/View.cpp, libautoscoper/src/View.hpp, libautoscoper/src/VolumeDescription.cpp, libautoscoper/src/VolumeDescription.hpp
Deprecates the use of `Autoscoper_BUILD_WITH_CUDA` CMake option in favor of `Autoscoper_RENDERING_BACKEND` option accepting values like `CUDA` or `OpenCL`
=> Add Autoscoper_RENDERING_BACKEND option

libautoscoper/src/View.cpp
* Remove second instance of deletion of the drrFilterBuffer Object from view.cpp
* For reference, the deletion of drrFilterBuffer_ was first introduced in https://github.com/BrownBiomechanics/Autoscoper/commit/6b7ad8e6b7d808f1aa117dfc863d2ecdb00a0586 (initial commit), then the duplicated deletion was later introduced through https://github.com/BrownBiomechanics/Autoscoper/commit/0a58d670e95e8e010dc1990ff22430a346d1c287 (Multibone initial : manual port of https://github.com/BrownBiomechanics/Autoscoper/commit/31ed16ca4064c98e71eaf703dbc4d00e48cc31db)
=> Fix OpenCL crashing on change trial

Superbuild/External_GLEW.cmake
* Removed usage of Sourceforge to download GLEW, moving to GitHub instead
* Closes Issue #50
=> Update GLEW superbuild to use GitHub

.gitignore, autoscoper/src/net/Socket.cpp, matlab/closeConnection.m
* Add MATLAB command closeConnection.m that sends a request to the autoscoper server to shutdown the client/server connection
* Update socket.cpp to support closing of the connection
* Closes Issue #53
=> Close client connection

libautoscoper/CMakeLists.txt
This commit fixes a regression introduced in 2adc328 (COMP: Simplify integration of GPU libraries leveraging transitive usage) that caused the configure error reported below when doing a "clean" build with the CUDA backend enabled.
The option `CUDA_LINK_LIBRARIES_KEYWORD` introduced in CMake 3.9 is now set to explicitly ensure a scope keyword is used in `CUDA_ADD_LIBRARY()`.
Configuration error:
```
-- Found CUDA: /usr/local/cuda (found version "10.2")
CMake Error at libautoscoper/CMakeLists.txt:43 (target_link_libraries):
The plain signature for target_link_libraries has already been used with
the target "libautoscoper".  All uses of target_link_libraries with a
target must be either all-keyword or all-plain.
The uses of the plain signature are here:
* …
```
=> COMP: Fix libautoscoper linking against CUDA libraries

libautoscoper/CMakeLists.txt, libautoscoper/src/PSO.cpp, libautoscoper/src/PSO.hpp, libautoscoper/src/Tracker.cpp, libautoscoper/src/gpu/cuda/PSO_kernel.h
* When the environment variable `Autoscoper_RANDOM_SEED` is set, it will be used for the random number generation in the PSO kernel.
=> Add option to specify seed for random number generation

scripts/python/PyAutoscoper/connect.py
* fixed issue with `closeConnection` in PyAutoscoper where after the connection to the server was severed the socket would wait indefinitely for the server.
=> Stop socket from waiting after closing connection

autoscoper/src/net/Socket.cpp, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, scripts/python/PyAutoscoper/connect.py
* Added ability to get the number of frames and number of volumes through the socket
* Updated PyAutoscoper to get frames and volumes
* PyAutoscoper 1.1.1
------------------- 
PyAutoscoper 1.1.1 is associated with the tag [python-client-v1.1.1](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/python-client-v1.1.1). Since it was created before this pull request was finalized, the code that will ultimately be integrated into the `main` branch will slightly be different.
The commit originally titled `BUG: Fix socket checking if file exists rather than path when saving data` that was initially associated with this pull request has been pushed into its pull request:
* https://github.com/BrownBiomechanics/Autoscoper/pull/93
=> Add support for retrieving # of volumes and frames over network

scripts/python/PyAutoscoper/connect.py
* Removed `close_connection` for improperly formatted input arguments, methods now exit gracefully with a warning
* Created custom exceptions `AutoscoperServerError` for when the server returns an unexpected value and `AutoscoperConnectionError` for when the connection to the server is lost unexpectedly. 
* Removed attribute `is_connected` and replaced with property `is_connected` to actively test the socket connection whenever needed
* Closes Issue #96 
* TODO: Create PyAutoscoper `v1.1.3` tag once this is merged.
=> Improve exception handling in pyautoscoper

Superbuild/External_GLEW.cmake
This commit fixes a regression introduced in e1d3d49 (`COMP: Update GLEW external project to download sources using Git`) through the following pull request:
* https://github.com/BrownBiomechanics/Autoscoper/pull/99
List of changes:
```
$ git shortlog 62d671f..8248234 --no-merges
Jean-Christophe Fillion-Robin (1):
Fix windows build copying generated *.rc files from glew-2.2.0 release
```
=> COMP: Update GLEW to fix windows build regression

CMake/autoscoper_set_env.bat.in, CMake/autoscoper_set_env.sh.in, CMakeLists.txt
* Decouple installing of shared libraries on windows from configuration of the launcher script.
* Add configuration of the launcher script in its own section and ensure the script is configured on macOS and Linux.
* Ensure the shell script has its executable bit set
* Retrieve Qt library directory without relying on the `_qt5Core_install_prefix`
internal variable.
* Add support for generating one launcher script per config. If a multi-config generator (e.g Visual Studio) is used, files like the following will be generated:
```
autoscoper_set_env-Debug.bat
autoscoper_set_env-MinSizeRel.bat
autoscoper_set_env-Release.bat
autoscoper_set_env-RelWithDebInfo.bat
```
=> Consolidate and improve launcher script generation

CMake/AutoscoperInstallQt.cmake, CMakeLists.txt, autoscoper/CMakeLists.txt
This commit introduces the option `Autoscoper_INSTALL_Qt_LIBRARIES` initialized to `ON` on Windows and `OFF` on the other platform where installing Qt is not supported.
A warning is displayed if option is enabled on a platform where the installation is not support.
=> COMP: Support enabling/disabling installation of Qt libraries

CMakeLists.txt
This removes the hard-coded install rules and relies on the install rules associated with each dependency built tree.
Also introduces the variable `Autoscoper_INSTALL_DEPENDENCIES` allowing to disable the installation.
=> COMP: Support installing dependencies across platform

CMake/AutoscoperInstallQt.cmake, CMakeLists.txt, autoscoper/CMakeLists.txt
This commit simplifies the install tree (and by extension the packaged tree) by avoiding to have both Debug & Release artifacts copied.
Instead of installing both `Release` and `Debug` artifacts into the same tree, each configuration may be installed in completely different directory.
For example:
```
cmake --install C:\path\to\Autoscoper-build\Autoscoper-build ^
--config Release ^
--prefix C:\path\to\Autoscoper-install-Release
```
=> COMP: Simplify install tree

CMake/autoscoper_set_env.sh.in, CMakeLists.txt, autoscoper/CMakeLists.txt
* Update `autoscoper_set_env.sh` to fix `LD_LIBRARY_PATH: unbound variable` error
* Ensure `autoscoper_set_env.sh` is executable
=> Fix autoscoper set env.sh

CMakeLists.txt
This commit addresses a warning like the following reported when building on Linux:
```
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first): …
```
=> COMP: Initialize OpenGL_GL_PREFERENCE and pass if down to inner-build

scripts/python/PyAutoscoper/connect.py
* Changed `AutoScoperServerError` to `AutoscoperServerError`
* Updated the function `getImageCropped`'s docstring to mention `AutoscoperServerError` and `AutoscoperConnectionError` rather than `Exception`
=> Fix typos in PyAutoscoper docstrings

autoscoper/src/ui/AutoscoperMainWindow.cpp
* Fixes a small bug that adds a trailing comma when saving the tracking data from a single volume that is not the last volume. 
* Before for a volume that is not the last one (bottom of the volume selector)
```
X_data, Y_data, Z_data, YAW_data, PITCH_data, ROLL_data,
```
* After
```
X_data, Y_data, Z_data, YAW_data, PITCH_data, ROLL_data
```
* This bug was causing errors when the tracking data was read by other programs (particularly the numpy csv reader).
=> BUG: Fix trailing comma when saving single volume tracking data

CMakeLists.txt, SuperBuild.cmake, autoscoper/CMakeLists.txt, libautoscoper/CMakeLists.txt
* Fix Slicer extension packaging allowing customizing autoscoper link flags introducing the CMake option `Autoscoper_EXECUTABLE_LINK_FLAGS`.
* Fix support for building on macOS introducing the option `Autoscoper_OPENCL_USE_ICD_LOADER` initialized to `TRUE` on Linux and Windows, and `FALSE` on macOS.
* Ensure `Autoscoper_*_DIR` variables are passed to inner build
* Add support for building Autoscoper as a regular executable on macOS introducing the CMake option `Autoscoper_MACOSX_BUNDLE`.
* Set `autoscoper_set_env.sh` permission flags only if CMake option `Autoscoper_CONFIGURE_LAUCHER_SCRIPT` is `ON`
* Remove obsolete comments from `autoscoper/CMakeLists.txt`
=> Restore support for building Autoscoper on macOS

Superbuild/External_TIFF.cmake
This change explicitly enables or disables codecs. By disabling unused or unavailable codecs, we can ensure that the library is not built with dependencies that are either not distributed or not available on the target system.
```
$ otool -L _CPack_Packages/Darwin/TGZ/31807-macosx-amd64-SlicerAutoscoperM-git0172c84-2023-06-23/Slicer.app/Contents/Extensions-31807/SlicerAutoscoperM/lib/Slicer-5.3/libtiff.5.8.0.dylib 
_CPack_Packages/Darwin/TGZ/31807-macosx-amd64-SlicerAutoscoperM-git0172c84-2023-06-23/Slicer.app/Contents/Extensions-31807/SlicerAutoscoperM/lib/Slicer-5.3/libtiff.5.8.0.dylib:
@rpath/Extensions-31807/SlicerAutoscoperM/lib/Slicer-5.3/libtiff.5.8.0.dylib (compatibility version 5.0.0, current version 5.8.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version …
```
=> COMP: Update TIFF external project explicitly enabling or disabling codecs

Documentation/getting-started.md
This should be merged only after these pull-requests have been integrated:
* #136 
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/35
=> DOC: Remove obsolete note mentioning extension is not available on macOS

README.md
=> DOC: Update README to include links to RTD and remove links to simtk

CMake/AutoscoperInstallQt.cmake
* Adds support for the installation of all Qt DLLs for `RelWithDebInfo` and `MinSizeRel` build configurations.
* These changes only affect builds configured with the option `Autoscoper_INSTALL_Qt_LIBRARIES` set to ON (the default on Windows)
_Issue originally found by @jacob-moore22_
=> Support installation of Qt DLLs for all build configurations

autoscoper/CMakeLists.txt, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/ui-files/AutoscoperMainWindow.ui
* If the configuration option `Autoscoper_INSTALL_SAMPLE_DATA` is set to `OFF` then the sample data menus in the `Help` menu with be disabled
* Closing #121 in favor of this PR
Related:
* https://github.com/BrownBiomechanics/Autoscoper/pull/121#pullrequestreview-1418594837
* https://github.com/BrownBiomechanics/Autoscoper/pull/29
=> Disable sample data menus if sample data is not installed

autoscoper/src/net/Socket.cpp, autoscoper/src/net/Socket.h, scripts/python/PyAutoscoper/connect.py
Autoscoper Server:
* New command `16`.
* Sends the `SERVER_VERSION` property over the TCP connection.
PyAutoscoper:
* New internal function `_checkVersion`.
* Called upon object init.
* Validates that the received server version matches the `EXPECTED_SERVER_VERSION` constant.
=> TCP socket version control

autoscoper/src/net/Socket.cpp, autoscoper/src/net/Socket.h, scripts/python/PyAutoscoper/connect.py
> Using semver for network protocols can be confusing. It's unclear
> what a change implies, even if backward compatible. This leads to
> unpredictable results when peers with different versions communicate.
> We rely on explicit, verbatim protocol negotiation instead. Semver is
> removed and replaced with ordinals that require explicit agreement
> without enforcing a specific policy for changes.
Adapted from https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/p2p-interface.md#why-do-we-version-protocol-strings-with-ordinals-instead-of-semver
This is a follow-up of:
* https://github.com/BrownBiomechanics/Autoscoper/pull/122
=> ENH: Simplify protocol versioning using ordinals instead of Semver

autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, autoscoper/src/ui/Manip3D.cpp, autoscoper/src/ui/Manip3D.hpp, autoscoper/src/ui/ui-files/AutoscoperMainWindow.ui
* Adds new menu `Accessibility` under the `View` dropdown with a toggleable option for thicker axis lines
* Addresses part of Issue #140 
| | Normal Lines | Thick Lines |
| --- | --- | --- |
| Translation | ![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/a2ba64ed-03b8-466d-9690-548404ae8008) | ![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/f88c1dbd-d9f1-49df-9fdf-3650d290c6c9) | 
| Rotation | ![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/9a35a262-fb16-4b20-b445-1c4465587340) | ![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/1f6b1569-232c-4b0f-ac23-5e6599359a1d) |
=> Add option for thicker axis lines for accessibility

autoscoper/src/ui/TrackingOptionsDialog.cpp
* Bug was caused by incorrect types being used (dividing two integers instead of two doubles)
* Bug was initially introduced during the initial implementation of the progress bar (See 681c3c7)
* Merging this PR will close #146 
* #131 Will be closed once the cancel button is working
=> Fix progress bar not updating

.github/workflows/python-publish.yml, .pre-commit-config.yaml, BUILD.md, CMake/autoscoper_set_env.bat.in, Documentation/_static/css/custom.css, Documentation/getting-started.md, Documentation/tutorials/loading-and-tracking.md, autoscoper/src/ui/AutoscoperMainWindow.cpp, scripts/matlab/AutoscoperConnection.m, scripts/matlab/README.md
Strip all trailing white spaces and enable "trailing-whitespace" pre-commit hook.
See https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace
For future reference, the following one liner was used:
```bash
for file in $(fd -t f -E *.tif -E *.png -E *.gif) $(fd -t f . .github/*); do
sed -i 's/[ \t]*$//' "$file";
done
```
=> Strip trailing whitespaces

Documentation/conf.py, Documentation/requirements.txt
This commit ensures that the generated API documentation using `automodule` is based of the PyAutoscoper version available along side the markdown files and not the latest version published on PyPI.
````rst
```{eval-rst}
.. automodule:: PyAutoscoper.connect
:members:
:undoc-members:
:show-inheritance:
```
````
=> DOC: Ensure generated PyAutoscoper API documentation is current

Documentation/socket-control-libraries/pyautoscoper.md, scripts/python/PyAutoscoper/connect.py, scripts/python/examples/pyautoscoper-examples.py
This is a follow-up of:
* https://github.com/BrownBiomechanics/Autoscoper/pull/161
=> BUG: Fix typo associated with OptimizationMethod enum

scripts/python/PyAutoscoper/connect.py
This is a follow-up of 04ebbaba5 (`DOC: Improve documentation related to parameter accepted as enum value`) and c57bcde76 (`DOC: Update PyAutoscoper example and default value to reference enums`)
=> DOC: Update PyAutoscoper docstrings to reference enums

autoscoper/src/ui/AutoscoperMainWindow.cpp, libautoscoper/src/Camera.cpp, libautoscoper/src/Trial.cpp
This commit is a follow-up of 4998f5b5d (COMP: Explicitly reference "std" namespace).
See https://cplusplus.com/reference/string/string/getline/
=> COMP: Explicitly reference "std" namespace for getline function

libautoscoper/src/Trial.cpp, libautoscoper/src/Trial.hpp
File without any "Version" key are considered to be version 1.0
This change is done anticipating the introduction of relative path support.
This pull request was created from work originally done in:
* https://github.com/BrownBiomechanics/Autoscoper/pull/125
* https://github.com/BrownBiomechanics/Autoscoper/pull/178
=> ENH: Add "Version" key to trial config file

libautoscoper/src/Trial.cpp
* `Trial.cpp(161,5): error C2440: 'return': cannot convert from 'std::filesystem::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'`
* Regression was initially introduced in 6f86beb56b31295b4c30c837a818818b021de4ee
* For future reference: [C2440](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?view=msvc-170&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2440)%26rd%3Dtrue)
=> COMP: Fix compile error C2440 in Trial.cpp

Documentation/tutorials/evaluating-tracking-results.md
This commit is a follow-up of 8d40491 (DOC: Add dedicated "Evaluating Tracking Results" tutorial)
It adds documented omitted while re-organizing the document in the context of:
* https://github.com/BrownBiomechanics/Autoscoper/pull/151
=> DOC: Add "Evaluating Tracking Results" tutorial document

libautoscoper/src/Trial.cpp, libautoscoper/src/Trial.hpp
Introduce `trimLineEndings()` function to remove both `\r` and `\n` characters from string. This ensures correct reading of values from .cfg files having `CRLF` line endings.
Note that given the size of the files, introducing a function like `safeGetline()` used in `Camera.cpp` would not significantly improve performance.
For comparison, here are timings for reading random strings of max 1000 characters with uniformly distributed lines endings:
| | trimLineEndings | safeGetline |
|--|--|--|
| 10000 lines (4.8M) | 66625 microseconds | 29825 microseconds |
| 100000 lines (48M)|  556135 microseconds | 266805 microseconds |
| 1000000 lines (~480M) | 5522480 microseconds | 2597533 microseconds|
=> BUG: Fix reading of .cfg file with CRLF line endings on Linux and macOS

libautoscoper/src/Trial.cpp, libautoscoper/src/Trial.hpp
Add the function `convertToUnixSlashes()` to systematically convert values associated with `mayaCam_csv`, `CameraRootDir` and `VolumeFile` keys to paths with Unix slashes that are supported on both Unix and Windows.
Approach was adapted from similar function found in `kwsys/SystemTools.cxx`[^1]
[^1]: https://gitlab.kitware.com/utils/kwsys/-/blob/c9f0da473ac2c21b25c1819141c4828dd238b4d3/SystemTools.cxx#L2125
=> BUG: Fix reading of .cfg file with backslash on Linux and Windows

scripts/python/pyproject.toml
Both Python 3.6 and 3.7 reached "end of life"
Latest release by Python version are the following:
* 3.6: 03 Sep 2021
* 3.7: 05 Jun 2023
See https://devguide.python.org/versions/
=> ENH: Update PyAutoscoper required python from 3.6 to 3.8

Superbuild/External_GLEW.cmake
This is a follow-up of 60b3d6ec0 (`COMP: Initialize OpenGL_GL_PREFERENCE and pass if down to inner-build`) to Address the following warning:
```
[  7%] Performing configure step for 'GLEW'
loading initial cache file /work/Preview/S-0-E-b/SlicerAutoscoperM-build/Autoscoper-build/GLEW-prefix/tmp/GLEW-cache-Release.cmake CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so …
```
=> COMP: Pass OpenGL_GL_PREFERENCE to GLEW project

scripts/python/PyAutoscoper/connect.py, scripts/python/pyproject.toml
_This pull request was created following https://github.com/BrownBiomechanics/Autoscoper/pull/183#issuecomment-1667146340_
Summary:
* Enables the `flake8-annotations` and `flake8-future-annotations` rules
* Updates PyAutoscoper to have type annotations.
Note that to support Python 3.8, it is required to add `from __future__ import annotations`
References:
* https://beta.ruff.rs/docs/rules/#flake8-annotations-ann
* https://beta.ruff.rs/docs/rules/#flake8-future-annotations-fa
* https://docs.python.org/3/library/__future__.html
=> Update Ruff settings enaling `flake8-annotations` rules

scripts/python/PyAutoscoper/connect.py
Following aab1e2a (`STYLE: Add type annotations to PyAutoscoper`), maintaining type information in docstrings is not needed anymore. The generated API documentation reports the types based on the type annotations.
=> DOC: Remove redundant sphinx directives duplicating type annotations

.readthedocs.yaml, Documentation/requirements.txt
From RTD build [21745032](https://readthedocs.org/projects/autoscoper/builds/21745032/):
```
Error
The configuration key "build.os" is required to build your documentation. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
```
From RTD build [21745423](https://readthedocs.org/projects/autoscoper/builds/21745423/):
```
Running Sphinx v7.2.4
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/autoscoper/envs/200/lib/python3.10/site-packages/sphinx/cmd/build.py", line 293, in build_main
app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
File "/home/docs/checkouts/readthedocs.org/user_builds/autoscoper/envs/200/lib/python3.10/site-packages/sphinx/application.py", line 233, in __init__
self.setup_extension(extension) …
```
=> Fix errors with RTD build

.readthedocs.yaml
* As of `2023-25-09` RTD will be failing builds that don't contain a `.readthedocs.yaml` config file as described [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#id1).
* See the [migration guide](https://blog.readthedocs.com/migrate-configuration-v2/) for more information
=> ENH: Update rtd config to minimum required ahead of cutoff

libautoscoper/src/Tracker.cpp
* Closes #203 
* See https://github.com/BrownBiomechanics/Autoscoper/issues/203#issuecomment-1708834168 for the reasoning behind the changes.
=> BUG: Fix incorrect conversion from viewport coordinates in tracker

CMake/FindJsonCpp.cmake, Documentation/file-specifications/camera-calibration.md, SuperBuild.cmake, Superbuild/External_JsonCpp.cmake, libautoscoper/CMakeLists.txt, libautoscoper/src/Camera.cpp, libautoscoper/src/Camera.hpp, libautoscoper/src/gpu/opencl/OpenCL.cpp, libautoscoper/src/schema/vtkCamera-schema-v1.0.json
* Adds a new camera loader for VTK cameras
* Defined as a `*.json` file
```json
{
"@schema": "https://autoscoperm.slicer.org/vtk-schema-1.0.json",
"version": 1.0,
"focal-point": [-7.9999999999999964, -245.50000000000006, -186.65000000000006],
"camera-position": [104.71926635196253, -255.22259800818924, -179.66771669788898],
"view-up": [0.0, 1.0, 0.0],
"view-angle": 30.0,
"image-width": 1760,
"image-height": 1760,
}
```
=> VTK Camera Loader

Documentation/file-specifications/config.md
* Closes #207 
* Update the config file specs
* Changes references to `camN` to `{task prefix}-camN`
* Changes config file name from `config.cfg` to `{task prefix}.cfg` 
* See [updated](https://autoscoper--208.org.readthedocs.build/en/208/file-specifications/config.html) documentation page preview.
=> Tweak naming convention for camera in cfg docs

libautoscoper/src/Tracker.cpp
* Switch back to the original conversion from viewport to pixel.
* The method integrated in PR #204 causes a performace slow down because of the larger images generated.
* A follow-up PR, #211 will be integrated to allow for the option of using the newer method
=> PERF: Switch back to original viewport conversion

autoscoper/CMakeLists.txt, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/VolumeDockWidget.cpp, autoscoper/src/ui/VolumeDockWidget.h, autoscoper/src/ui/VolumeListWidgetItem.cpp, autoscoper/src/ui/VolumeListWidgetItem.h, autoscoper/src/ui/ui-files/VolumeDockWidget.ui, libautoscoper/src/gpu/opencl/RayCaster.cpp, libautoscoper/src/gpu/opencl/RayCaster.hpp
* Closes #206 
* Adds a toggle to each volume to allow the user to switch on and off which volumes are being displayed.
* Note: If a volume is toggled off, it will be disabled visually and during any optimizations.
=> Add option to enable/disable a single DRR

libautoscoper/src/PSO.cpp
* Closes #217 
| method/`rand()` return val | `0` | `RAND_MAX` |
| --- | ---- | --- |
| Old | `low ` | `≈(high+1)` *| 
| New | `low` | `high` |
*Since, previously, we were scaling by `RAND_MAX/(RAND_MAX+1)` the computed value is going to be extremely close to , but slightly lower, than `high+1`
=> BUG: Fix getRandom() returning values above max limit

libautoscoper/src/gpu/cuda/RayCaster.cpp, libautoscoper/src/gpu/cuda/RayCaster.hpp
* error C2039: 'setVisible': is not a member of 'xromm::gpu::RayCaster'
* Regression introduced in 103df1a
=> Fix CUDA RayCaster not having setVisible member

libautoscoper/src/PSO.cpp, libautoscoper/src/PSO.hpp, libautoscoper/src/Tracker.cpp
* For any given particle p, this update removes any recomputation of the NCC fitness value.
* Replaces arrays with vectors
* This drops the per frame opt time from ~9 to ~18 seconds to around ~3 to ~ 6 seconds
* Based off of #221 
* It would appear that most of the time gained was from these API changes, however, there still is ~.5 sec per frame left on the table from adding the multithreading.
=> PERF: Introduce particle data structure for PSO

libautoscoper/src/PSO.cpp, libautoscoper/src/PSO.hpp, libautoscoper/src/Tracker.cpp
:warning: This pull request was created to include the changes originally included through this pull-request https://github.com/BrownBiomechanics/Autoscoper/pull/223
For the sake of having a clean history and considering the updated `main` branch has not been referenced externally, `main` was forced push to https://github.com/BrownBiomechanics/Autoscoper/commit/73eb359dcd70878c4b4c28471fd2684c08bd3014
----------
Refactor the Particle Swarm Optimization (PSO) implementation by introducing a specialized Particle data structure alongside a particle collection. This structure allows us to efficiently manage and track computed Normalized Cross-Correlation (NCC) values for each particle. As a result, we now evaluate each particle only once per iteration, as opposed to between 2 and 5 times in …
=> PERF: Introduce particle data structure for PSO (#223)

libautoscoper/src/PSO.cpp
Since we started initializing the position to be `{0., 0., 0., 0., 0., 0.}` the call to `push_back` is not needed.
=> BUG: Fix PSO Particle struct position initialization

libautoscoper/src/Camera.cpp, libautoscoper/src/Tracker.cpp, libautoscoper/src/Tracker.hpp
After meeting with @amymmorton this approach may be the way to move forward. However, a deeper dive into the geometry and the projections will likely need to be done later on.
This PR introduces the following:
*  Computation of the bounds of the radiograph image on the film plane (located at z = -2 or 2 units in front of the camera)
* Checking that the 2D DRR image falls within the bounds of the radiograph
* Clipping the bounds of the 2D DRR image to be at most the bounds of the radiograph
Successfully merging this PR should close the following PRs and issues:
* Closes #203
* Closes #229
* Closes #211
| Position in Autoscoper | Left Cam | Right Cam | 
| --- | ---- | --- |
| ![image](https://github.com/BrownBiomechanics/Autoscoper/assets/30351234/970be6fa-d46c-49dd-a94b-1e0ca3550e6e) | …
=> BUG: Clip bounds of DRR projection to the bounds of the radiograph

CMakeLists.txt, autoscoper/CMakeLists.txt, libautoscoper/CMakeLists.txt
The option `Autoscoper_ARTIFACT_SUFFIX` allows users to specify a custom suffix to be appended to the names of Autoscoper artifacts, aiding in the unique identification of artifacts based on selected build options.
This is done anticipating the support for packaging multiple backend-specific versions of Autoscoper in `SlicerAutoscoperM`.
=> COMP: Add support for appending a suffix to Autoscoper artifacts

libautoscoper/src/gpu/cuda/cutil/cutil_gl_inline.h, libautoscoper/src/gpu/cuda/cutil/cutil_inline_runtime.h
This commit addresses compilation errors against SDKs that do not have the `cufft` library installed. The update includes the introduction of the `HAVE_CUFFT` macro, which selectively excludes the relevant code. It's important to note that Autoscoper does not utilize `cufft` functionality.
=> COMP: Update cutil headers to fix build against SDK without cufft library

CMakeLists.txt
If the main project has been configured specifying the variable `CUDA_TOOLKIT_ROOT_DIR`, this propagates the variable to the inner-build.
=> COMP: Ensure Autoscoper inner-build is built with expected CUDA toolkit

libautoscoper/src/gpu/cuda/BackgroundRenderer.cpp, libautoscoper/src/gpu/cuda/BackgroundRenderer_kernels.cu, libautoscoper/src/gpu/cuda/BackgroundRenderer_kernels.h, libautoscoper/src/gpu/cuda/Compositor_kernels.cu, libautoscoper/src/gpu/cuda/DRRBackground_kernels.cu, libautoscoper/src/gpu/cuda/Merger_kernels.cu, libautoscoper/src/gpu/cuda/Mult_kernels.cu, libautoscoper/src/gpu/cuda/RadRenderer.cpp, libautoscoper/src/gpu/cuda/RadRenderer_kernels.cu, libautoscoper/src/gpu/cuda/RadRenderer_kernels.h, libautoscoper/src/gpu/cuda/RayCaster.cpp, libautoscoper/src/gpu/cuda/RayCaster_kernels.cu, libautoscoper/src/gpu/cuda/RayCaster_kernels.h, libautoscoper/src/gpu/cuda/cutil/cutil_create_tex_obj.h
* Replace outdated texture references with texture objects (added in CUDA 5.0) for CUDA 12.0
* Closes issues 
* #42 
* #72
* #241  
* For future reference see https://developer.nvidia.com/blog/cuda-pro-tip-kepler-texture-objects-improve-performance-and-flexibility/
=> Update texture references to texture objects

libautoscoper/src/gpu/cuda/RayCaster.cpp
Bug was introduced in commit 73eb359dcd70878c4b4c28471fd2684c08bd3014
=> BUG: Ensure CUDA RayCaster is sets visible to true by default

autoscoper/src/net/Socket.cpp, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, autoscoper/src/ui/VolumeDockWidget.cpp, autoscoper/src/ui/VolumeDockWidget.h, autoscoper/src/ui/VolumeListWidgetItem.cpp, autoscoper/src/ui/VolumeListWidgetItem.h, scripts/matlab/AutoscoperConnection.m, scripts/python/PyAutoscoper/connect.py
- Closes #247 
- Adds Socket control for toggling the visibility of DRRs
- Defaults the visibility flag in the CUDA backend to `true`
- @amymmorton I don't have an active MATLAB license anymore, could you test the updated class?
-  ~~**Note:** I haven't set the UI to update yet so the checkbox will still be checked~~
ToDo:
=> ENH: Socket control drr visibility toggle

CMakeLists.txt, libautoscoper/CMakeLists.txt
See https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html
> The [FindCUDA](https://cmake.org/cmake/help/latest/module/FindCUDA.html#module:FindCUDA) module has been deprecated since CMake 3.10. CMake 3.27 and above prefer to not provide the module. This policy provides compatibility for projects that have not been ported away from it.
Source: https://cmake.org/cmake/help/latest/policy/CMP0146.html
* Closes #89
=> ENH: Modernize CUDA integration using FindCUDAToolkit CMake module

.clang-format, libautoscoper/src/gpu/cuda/cutil/.clang-format
Relocate `.clang-format` file into the `cutil` sub-directory where the use of `extern` statement require setting `BreakBeforeBraces` to `Custom`.
Remove commented code from main configuration file.
=> STYLE: Cleanup clang-format configuration files

autoscoper/src/ui/AutoscoperMainWindow.cpp
* Closes #250 
This functionality was originally disabled in commit 11c2488a
After reaching out to @BardiyaAk he stated that "I remember the Delete key was buggy and messing things up, specifically it wasn’t performing as intended when the frame was not inserted/optimized."
However, through my testing, I have not been able to reproduce any errors.
=> ENH: Reenable original delete functionality

libautoscoper/src/gpu/cuda/cutil/cutil_create_tex_obj.h
Fix #264 by addressing a regression introduced in 866a5d2 ("ENH: Add support for 16 and 32-bit radiograph images", 2023-01-13)
This ensures the texture clamping mode is consistently set across all dimensions.
=> BUG: Fix rendering of 3D texture associated with the CUDA backend

autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/FilterTreeWidget.cpp, autoscoper/src/ui/FilterTreeWidgetItem.cpp, autoscoper/src/ui/ModelViewTreeWidgetItem.cpp, libautoscoper/CMakeLists.txt, libautoscoper/src/Camera.cpp, libautoscoper/src/Trial.cpp, libautoscoper/src/asys/SystemTools.cxx, libautoscoper/src/asys/SystemTools.hxx
This commit addresses a bug where files saved on Windows platforms using `\r\n` line endings were not correctly read on Unix platforms using `\n`. To resolve this issue, the commit introduces the function `GetLineFromStream()` to consistently read lines from text files independent of the line ending conventions.
Additionally, this commit removes the complex `safeGetline` function, which aimed to achieve similar behavior. Originally sourced from Stack Overflow[^1] and introduced in commit 243123c ("Added support for MayaCam version 2", dated 2018-01-11).
[^1]: https://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf/6089413#6089413
=> BUG: Ensure consistent handling of line endings when reading trial/filters/camera files

libautoscoper/src/Tracker.cpp
Regression introduced in 4704f9b ("BUG: Clip bounds of DRR projection to the bounds of the radiograph", 2023-11-01).
Previously whenever a volume was outside the bounds of a radiograph image the NCC value would be appended as 0. In this case it is possible that the PSO could try to move the volume to be outside the bounds of all the radiographs.
Related pull requests:
* https://github.com/BrownBiomechanics/Autoscoper/pull/230
=> BUG: Fix out of bounds NCC value in viewport clipping

libautoscoper/src/Tracker.cpp, math/Quaternion.hpp
Closes #275 
Regression initially introduced in 6b7ad8e. Slerp interpolation fails in some cases when t == 0 or t == 1
=> BUG: Fix edge cases in Slerp

Documentation/file-specifications/camera-calibration.md, libautoscoper/src/schema/vtkCamera-schema-v1.0.json
Updates camera schema ahead of https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/75
=> ENH: Update schema

autoscoper/src/ui/AutoscoperMainWindow.cpp
Fix regression introduced in 4d2eec3 (changes similar to https://github.com/BrownBiomechanics/Autoscoper/commit/77dc0ee17e2303bbab380dde455d3ea8047d0881)
=> BUG: Add missing conversion from quaternion to eulers in getPose

Documentation/shortcuts.md, autoscoper/src/ui/AdvancedOptionsDialog.cpp, autoscoper/src/ui/AdvancedOptionsDialog.h, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, autoscoper/src/ui/TimelineDockWidget.cpp, autoscoper/src/ui/TimelineDockWidget.h, autoscoper/src/ui/ui-files/AdvancedOptionsDialog.ui, autoscoper/src/ui/ui-files/TimelineDockWidget.ui
Adds support for manipulating DRR position using the arrow keys.
Controls:
* `Left`  Select previous DOF. 
* `Right` Select next DOF. 
* `Up`  Increment selected DOF. 
* `Down`  Decrement selected DOF. 
Selected DOF is bolded on the timeline
Vary the step size by going to `Tracking-> Advanced Settings -> Step Size` defaults to `1mm/deg`
Closes #285
=> Fine grain dof adjustment

autoscoper/src/ui/ui-files/TrackingOptionsDialog.ui
=> BUG: Fix tab order in tracking dialog UI

Documentation/shortcuts.md, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, libautoscoper/src/CoordFrame.cpp, libautoscoper/src/CoordFrame.hpp, libautoscoper/src/Tracker.cpp, libautoscoper/src/Tracker.hpp, libautoscoper/src/VolumeDescription.hpp
* Closes #284 
* Closes #286 
* Adds shortcut `O` to align the manipulator axes to the global axes
* Adds shortcut `P` to snap the pivot back to the center of the volume
=> Pivot alignment and centering

CONTRIBUTING.md, Documentation/tutorials/pre-processing-module.md
Small fixes to various markdown bugs across the SlicerAutoscoperM docs.
Namely, the image included in the [pre-processing module](https://autoscoper.readthedocs.io/en/latest/tutorials/pre-processing-module.html#accessing-the-pre-processing-module) section of the tutorial was missing due to a broken link
and the links for the Autoscoper forum and issue tracker were not being formatted correctly in multiple places on the [Contributing page](https://autoscoper.readthedocs.io/en/latest/developer-guide/contributing.html)
=> DOC: Fix ill-formatted links and missing image

Documentation/file-specifications/camera-calibration.md, Documentation/getting-started.md, Documentation/tutorials/pre-processing-module.md
Updates the documentation to reflect the removal of the VRG generation functionality in https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/140, as requested by https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/132.
See the docs for this branch [here](https://autoscoper--307.org.readthedocs.build/en/307/file-specifications/camera-calibration.html)
=> DOC: Deprecate camera calibration file spec and remove VRG references

Documentation/file-specifications/config.md, Documentation/tutorials/pre-processing-module.md
Updates to the documentation page for the Pre-Processing module to reflect the changes in https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/141
Review the changes [here](https://autoscoper--308.org.readthedocs.build/en/308/tutorials/pre-processing-module.html).
=> DOC: Update documentation for Pre-Processing config generation

Documentation/conf.py, Documentation/index.md, Documentation/requirements.txt, Documentation/transforms.md
Closes #280, closes https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/148
See [RTD page](https://autoscoper--300.org.readthedocs.build/en/300/transforms.html)
TODO:
=> DOC: Include description of pre-processing transforms

Documentation/getting-started.md
Frame-level tracking via the AutoscoperM executable requires a GPU rendering backend and is therefore only supported on Linux and Windows. macOS is not supported due to rendering-backend limitations.
=> DOC: Clarify AutoscoperM platform rendering constraints
