CONTRIBUTING.md
This document is based on 3D Slicer guidelines.
See https://github.com/Slicer/Slicer/blob/v5.0.3/CONTRIBUTING.md
=> DOC: Add contributing guidelines

CMakeLists.txt, autoscoper/CMakeLists.txt, cmake/ExternalProject.cmake, cmake/MessageMacros.cmake, cmake/UseGLEW.cmake, cmake/UseLIBTIFF.cmake, libautoscoper/CMakeLists.txt
Summary of changes:
* Use 2 spaces for block indentation
* Remove redundant empty lines
* Remove extra spaces in CMake function, macro and command calls
=> STYLE: Update CMake sources to use consistent indentation and spacing

CMake/AutoscoperInstallQt.cmake, autoscoper/CMakeLists.txt
* <s>Remove explicit use of  Qt5*_LIBRARIES and Qt5*_INCLUDE_DIRS</s>
* Move installation of Qt5 to a dedicated module
* Closes #17
=> Qt5 module

CMake/ExternalProjectDependency.cmake, CMakeLists.txt, SuperBuild.cmake, Superbuild/External_GLEW.cmake, Superbuild/External_TIFF.cmake
=> Update build-system to use ExternalProjectDependency.cmake

matlab/README.md
In addition of the usual [File changed](https://github.com/BrownBiomechanics/Autoscoper/pull/6/files) interface for adding suggestions, the document contributed through this pull request can also be reviewed in its rendered form [here](https://github.com/jcfr/Autoscoper/blob/add-matlab-interface-doc/matlab/README.md)
=> Add "Autoscoper Matlab TCP client" document

libautoscoper/src/gpu/opencl/OpenCL.cpp, libautoscoper/src/gpu/opencl/OpenCL.hpp
=> Fix memory leak in OpenCL backend

libautoscoper/src/gpu/cuda/BackgroundRenderer.cpp, libautoscoper/src/gpu/cuda/BackgroundRenderer_kernels.cu, libautoscoper/src/gpu/cuda/BackgroundRenderer_kernels.h, libautoscoper/src/gpu/cuda/RadRenderer.cpp, libautoscoper/src/gpu/cuda/RadRenderer_kernels.cu, libautoscoper/src/gpu/cuda/RadRenderer_kernels.h, libautoscoper/src/gpu/cuda/RayCaster.cpp, libautoscoper/src/gpu/cuda/RayCaster_kernels.cu, libautoscoper/src/gpu/cuda/RayCaster_kernels.h
This reverts commit d2fc1fa33847cd5247a6c8ec47b8dc8b0783e8de.
=> Revert changes to CUDA code accidentally introduced

scripts/matlab/AutoscoperConnection.m, scripts/matlab/README.md
@kaitohl  found a data type inconsistency in the getNCC imbedded functions- we stepped through each to resolve.
=> BUG: NCC return function corrections matlab socket class

scripts/matlab/AutoscoperConnection.m
hoping this branch passes commit message test - frustrating.
close connection hung in inf loop after fwrite - commented out, now functioning
=> Close connection inf loop fix

autoscoper/src/net/Socket.cpp, autoscoper/src/net/Socket.h, scripts/matlab/AutoscoperConnection.m, scripts/python/PyAutoscoper/connect.py
This pull request is a follow-up to:
* https://github.com/BrownBiomechanics/Autoscoper/pull/84
=> Improve close connection support

libautoscoper/src/gpu/opencl/OpenCL.cpp, libautoscoper/src/gpu/opencl/OpenCL.hpp
Added functions for creating 3D kernels in OpenCL.
Will be needed by #87
=> ENH: Update OpenCL wrapper to support 3D kernels

scripts/python/PyAutoscoper/connect.py, scripts/python/pyproject.toml
This offers a reasonable trade-off in term of consistency and readability.
=> STYLE: Update "line-length" black settings from 88 to 120

LICENSE, README.md
Format adapted from:
* https://github.com/Slicer/Slicer/pull/5658
=> Add top level license file

.pre-commit-config.yaml
* Update pre-commit config to ensure black always uses expected settings
* Update black version specified in pre-commit config
=> Update pre commit black integration

autoscoper/src/net/Socket.cpp
This commit removes the hard-coded offset introducing the convenience macro `SocketReadValuePointerMacro`.
This will allows to introduce new field values without having to manually recompute all offsets.
=> ENH: Improve robustness of message field reading anticipating updates

.git-blame-ignore-revs
=> STYLE: Ignore trailing white spaces changes in blame history

scripts/python/PyAutoscoper/connect.py
This pull request was created based on changes originally associated with the following one:
* https://github.com/BrownBiomechanics/Autoscoper/pull/119
=> ENH: Improve API usability introducing enums

scripts/python/PyAutoscoper/connect.py
This pull request was created based on changes originally associated with:
* https://github.com/BrownBiomechanics/Autoscoper/pull/119
* https://github.com/BrownBiomechanics/Autoscoper/pull/161
=> Improve pyautoscoper tracking dialog default values

Documentation/socket-control-libraries/pyautoscoper.md, scripts/python/examples/pyautoscoper-examples.py
This is a follow-up of 04ebbaba5 (DOC: Improve documentation related to parameter accepted as enum value)
=> DOC: Update PyAutoscoper example and default value to reference enums

scripts/python/PyAutoscoper/connect.py
This commit fixes a regression originally introduced in 2f7ae7f83 (ENH: Add Error checking to socket)
=> BUG: Fix invocation of optimizeFrame in PyAutoscoper trackingDialog

Documentation/socket-control-libraries/matlab.md, Documentation/socket-control-libraries/pyautoscoper.md, autoscoper/src/net/Socket.cpp, scripts/matlab/AutoscoperConnection.m, scripts/python/PyAutoscoper/connect.py, scripts/python/examples/pyautoscoper-examples.py
* Updated PyAutoscoper and the MATLAB client to allow the user to specify an optimization initialization heuristic (initial guess), as seen in the tracking dialog from the Autoscoper GUI.
* Updated the `socket.cpp` to support these changes
* <s>Added Enums to PyAutoscoper for `InitialGuess`, `CostFunction`, and `OptimizationMethod` to make setting optimization options more user-friendly.</s>
* Added `OptimizationInitializationHeuristic`
Once the following pull request will be merged, the tag for `PyAutoscoper v1.2.0`:
* #118
* #122
Once the support for protocol versioning is merged, the `AUTOSCOPER_SOCKET_VERSION` and `EXPECTED_SERVER_VERSION` properties will be updated in `Socket.cpp` and `PyAutoscoper/connect.py` respectively. 
* #122
=> Pyautoscoper initial guess

autoscoper/src/ui/AutoscoperMainWindow.cpp
* Add check to validate there are nodes to be removed
* Fixes a regression initially introduced in 11c2488
* Closes #172
=> BUG: Delete key attempts to remove non-existent nodes

libautoscoper/src/Trial.cpp, libautoscoper/src/Trial.hpp
This change is done anticipating the introduction of versioning and relative path support.
This pull request was created from work originally done in:
* https://github.com/BrownBiomechanics/Autoscoper/pull/125
=> STYLE: Refactor Trial introducing parse/validate/load functions

autoscoper/src/net/Socket.cpp, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h
This was created while working on:
* https://github.com/BrownBiomechanics/Autoscoper/pull/182
=> Improve error reporting for tracking data load

Documentation/getting-started.md, Documentation/index.md, Documentation/shortcuts.md, Documentation/tutorials/custom-data.md, Documentation/tutorials/index.md, Documentation/tutorials/loading-and-tracking.md, Documentation/tutorials/saving-and-resuming-tracks.md, Documentation/tutorials/tips-and-tricks.md, autoscoper/src/ui/AutoscoperMainWindow.cpp
* Updates for the tutorials based on the feedback from #140 
* Closes #140 
* [Autogenerated Documentation Preview](https://autoscoper--142.org.readthedocs.build/en/142/)
=> Update Tutorial based on feedback 

autoscoper/src/ui/AutoscoperMainWindow.cpp, libautoscoper/src/Video.cpp, libautoscoper/src/Video.hpp
=> Fix incorrect and no support for background image calculations of 16 and 32 bit radiographs

autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, autoscoper/src/ui/FilterDockWidget.cpp, autoscoper/src/ui/FilterDockWidget.h, autoscoper/src/ui/FilterTreeWidget.cpp, autoscoper/src/ui/FilterTreeWidget.h, libautoscoper/src/Tracker.cpp, libautoscoper/src/Tracker.hpp
* Closes #252 
Will generate a log file named `{unix timestamp}_{trial name}.log` to a `Logs` subdir:
```
Task Name: flx_ext
OptimizationParameters: 
repeats: 1
dframe: 1
method: 0
max_iter: 1000
min_limit: -3
max_limit: 3
cf_model: 0
max_stall_iter: 25
opt_init_heuristic: 0
camera_begin 0
RadFilters_begin
SobelFilter_begin
Scale 0.43
Blend 3
SobelFilter_end
ContrastFilter_begin
Alpha 2.5
Beta 0.9
ContrastFilter_end
RadFilters_end
DrrRenderer_begin
SampleDistance 0.62
RayIntensity 0.35
Cutoff 0
DrrRenderer_end
DrrFilters_begin
SobelFilter_begin
Scale 0.1
Blend 1.7
SobelFilter_end
DrrFilters_end
camera_end 0
camera_begin 1
RadFilters_begin
SobelFilter_begin
Scale 0.43
Blend 3
SobelFilter_end
ContrastFilter_begin
Alpha 2.5
Beta 0.9
ContrastFilter_end
RadFilters_end
DrrRenderer_begin …
```
=> ENH: Add log file generation

autoscoper/src/ui/VolumeListWidgetItem.cpp
=> BUG: Fix Volume item selection area

.git-blame-ignore-revs
Follow-up of:
* https://github.com/BrownBiomechanics/Autoscoper/pull/260
=> STYLE: Ignore source files formatting changes in blame history

autoscoper/src/ui/AutoscoperMainWindow.cpp
=> BUG: Add missing conversion from quaternion to eulers

libautoscoper/src/Tracker.cpp
=> BUG: Fix incorrect application of input heuristics

Documentation/shortcuts.md, autoscoper/src/ui/AutoscoperMainWindow.cpp, autoscoper/src/ui/AutoscoperMainWindow.h, autoscoper/src/ui/FilterDockWidget.cpp, autoscoper/src/ui/FilterDockWidget.h, autoscoper/src/ui/FilterTreeWidget.cpp, autoscoper/src/ui/FilterTreeWidget.h
Added shortcut `L` to toggle radiograph images on and off
closes #290
=> ENH: Add toggle radiograph shortcut

Documentation/tutorials/hierarchical-3d-registration.md
@sbelsk I should have waited to add this to the previous #311 .. I honestly didn't think testing 4dct was going to go so smoothly - enough to generate success graphics on the first go!!
=> DOC: Successful 4DCT registration media

Documentation/about.md, Documentation/file-specifications/camera-calibration.md, Documentation/getting-started.md, Documentation/index.md, Documentation/tutorials/custom-data.md, Documentation/tutorials/hierarchical-3d-registration.md, Documentation/tutorials/index.md
Prompted by a recent email query wrt calibration and xmalab use by:
Jason R. Franz, Ph.D. via mobile
Associate Professor
Lampe Joint Department of Biomedical Engineering
University of North Carolina at Chapel Hill
North Carolina State University
=> Xmalab link included in documentation and updated tutorial overview description
